# Generated by Django 3.2.6 on 2022-03-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0002_folder_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.project'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesystem.folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.project')),
            ],
        ),
    ]
