# Generated by Django 3.2.6 on 2022-03-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0004_folder_node'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folder',
            new_name='Directory',
        ),
    ]
