# Generated by Django 3.2.6 on 2022-03-01 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0005_rename_folder_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='folder',
        ),
        migrations.AddField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesystem.directory'),
        ),
    ]
