# Generated by Django 3.2.6 on 2022-03-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0006_auto_20220301_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='parent_folder',
            new_name='parent_directory',
        ),
    ]
