# Generated by Django 3.2.6 on 2022-03-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0007_rename_parent_folder_directory_parent_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='build',
            field=models.TextField(default='<!--Build File-->'),
            preserve_default=False,
        ),
    ]
